# Site settings
title: Sometimes I like (write) things...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kevin-ohara.github.io" # the base hostname & protocol for your site
twitter_username: kev_ohara
github_username:  kevin-ohara

# Build settings
markdown: kramdown

kramdown:
  input: GFM
